author: SwearWord
main: org.blockface.careers.Careers
name: Careers
url: http://blockface.org/
version: '2.0'
commands:
    setjob:
        description: Set job.
        usage: /setjob <career> [player];
    jobinfo:
        description: See info about job.
        usage: /info
    addexp:
        description: Add experience points.
        usage: /addexp <number>
